import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { catalogFields, hasInputField, selectInputField } from '../lib/input-selection.ts';
const defaults = JSON.parse(readFileSync(new URL('../public/demo/defaults.json', import.meta.url), 'utf8'));
const template = JSON.parse(readFileSync(new URL('../public/demo/input-catalog.json', import.meta.url), 'utf8'));
const fields = catalogFields(template);
assert.equal(new Set(fields.map(f => f.table)).size, 8);
assert.ok(fields.length > 70);
let selected = structuredClone(defaults.inputs);
for (const field of fields) selected = selectInputField(selected, template, field.path, true);
assert.deepEqual(selected.output_schema, template.output_schema);
assert.deepEqual(selected.mappings, template.mappings);
selected = selectInputField(selected, template, ['accounts', 'movements', 'amount'], false);
assert.equal(hasInputField(selected, ['accounts', 'movements', 'amount']), false);
assert.ok(hasInputField(selected, ['accounts', 'movements', 'date']));
assert.equal(selected.mappings.accounts.array.movements.join, 'movements');
for (const field of fields.filter(f => f.path[0] === 'addresses')) selected = selectInputField(selected, template, field.path, false);
assert.equal(selected.output_schema.fields.addresses, undefined);
selected = selectInputField(selected, template, ['addresses', 'city'], true);
assert.deepEqual(Object.keys(selected.output_schema.fields.addresses.items.fields), ['city']);
assert.deepEqual(Object.keys(selected.mappings.addresses.array), ['city']);
const old = structuredClone(defaults.inputs);
old.sources = old.sources.filter((s: any) => !['e', 'ad', 'it'].includes(s.id));
old.joins = old.joins.filter((j: any) => !['employment', 'addresses', 'interactions'].includes(j.id));
old.created_by = 'existing-user';
const upgraded = selectInputField(old, template, ['employment', 'company'], true);
assert.equal(upgraded.created_by, 'existing-user');
assert.ok(upgraded.sources.some((s: any) => s.id === 'e'));
assert.equal(old.sources.some((s: any) => s.id === 'e'), false);
console.log(`PASS: ${fields.length} selectable fields across 8 tables; granular arrays, sibling preservation, empty branch removal and old drafts.`);
