import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transition} from '../lib/workflow.ts';
const defaults=JSON.parse(readFileSync(new URL('../public/demo/defaults.json',import.meta.url),'utf8'));
let s={...defaults,history:[],audit:[],currentProducts:{}};
assert.throws(()=>transition(s,{action:'save',kind:'inputs',persona:'specialist',document:defaults.inputs}));
assert.throws(()=>transition(s,{action:'submit',kind:'evaluations',persona:'specialist'}));
s=transition(s,{action:'submit',kind:'inputs',persona:'policy'});
const id=s.history[0].id;
assert.throws(()=>transition(s,{action:'approve',id,persona:'policy'}));
s=transition(s,{action:'approve',id,persona:'po'});
assert.equal(s.currentInput.definition_version,1);
assert.throws(()=>transition(s,{action:'approve',id,persona:'po'}));
const modified=structuredClone(defaults.inputs);modified.definition_id='banking_inputs';modified.created_by='different';
assert.throws(()=>transition(s,{action:'save',kind:'inputs',persona:'policy',document:modified}),/publicada/);
s=transition(s,{action:'submit',kind:'evaluations',persona:'specialist'});
s=transition(s,{action:'reject',id:s.history[0].id,persona:'po',reason:'Revisar política'});
assert.equal(s.history[0].status,'rejected');
s=transition(s,{action:'submit',kind:'evaluations',persona:'specialist'});
s=transition(s,{action:'approve',id:s.history[0].id,persona:'po'});
assert.equal(Object.keys(s.currentProducts).length,3);
const next=structuredClone(defaults.evaluations);next.definition_version=2;
s=transition(s,{action:'save',kind:'evaluations',persona:'specialist',document:next});
s=transition(s,{action:'submit',kind:'evaluations',persona:'specialist'});
s=transition(s,{action:'approve',id:s.history[0].id,persona:'po'});
assert.equal(Object.keys(s.currentProducts).length,3);
assert.equal(s.currentProducts.demo_credit.definition_version,2);
assert.throws(()=>transition(s,{action:'save',kind:'evaluations',persona:'variables',document:{...next,rules:[]}}));
console.log('PASS: permissions, immutable publications, rejection/resubmission and one active evaluation per product.');
